### PR TITLE
Implementing the HTTP-POST IDP Logout Request

### PR DESCRIPTION
**Pull request by gurtzoo**
Implementing the HTTP-POST IDP Logout Request.
Modifications as also removing some trailing spaces and convert some tabs to spaces.

### CODE REVIEW

**Comment by gurtzoo** [comment]
Is the project still active?

**Comment by thijskh** [comment]
It's surely active, but I don't think you can expect reviews to be within a specific time frame, especially during the holidays.

**Comment by thijskh** [comment]
At a first look I see many whitespace changes that make this PR hard to review. Please confine your commit to the actual functional changes, and put any whitespace changes (if they are needed) in a separate commit.

**Comment by gurtzoo** [comment]
I will redo another pull request

**Pull request closed without merging**
